name: mobilpedia_fe
description: A new MobilPedia Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/logo.png
    - assets/bmw.jpg
    - assets/ferari.jpg
    - assets/lambo.jpg
    - assets/ferarri.jpg
    - assets/bmww.jpg
    - assets/poce.jpg
    - assets/bugati.jpg
    - assets/splash.jpg
    - assets/log.jpg
    # - assets/images/home_profile.png
    # - assets/images/home_ad_lamborghini.png


  # Kalo mau pakai custom font (opsional)
fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto1.ttf
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700